http_port 3128
icap_enable on
icap_service service_resp respmod_precache bypass=0 icap://127.0.0.1:1344/respmod
adaptation_access service_resp allow all
acl localnet src 10.0.0.0/24
http_access allow localnet
