#
# Labtainer Dockerfile - audio_phase_ptit
# Bài thực hành: Kỹ thuật giấu tin bằng mã hóa pha (Phase Coding)
# PTIT - Học viện Công nghệ Bưu chính Viễn thông
#
ARG registry
FROM $registry/labtainer.base2

ARG lab
ARG labdir
ARG imagedir
ARG user_name
ARG password
ARG apt_source
ARG version
LABEL version=$version
ENV APT_SOURCE $apt_source
RUN /usr/bin/apt-source.sh
RUN sed -i 's/http:/https:/g' /etc/apt/sources.list

# Cài đặt các thư viện cần thiết
RUN apt-get update -y && apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    python3-numpy \
    && rm -rf /var/lib/apt/lists/*

# Thêm file hệ thống
ADD $labdir/$imagedir/sys_tar/sys.tar /
ADD $labdir/sys_$lab.tar.gz /

# Tạo user sinh viên
RUN useradd -ms /bin/bash $user_name
RUN echo "$user_name:$password" | chpasswd
RUN adduser $user_name sudo

# Chuyển sang user và thêm file thực hành
USER $user_name
ENV HOME /home/$user_name

ADD $labdir/$imagedir/home_tar/home.tar $HOME
RUN rm -f $HOME/home.tar
ADD $labdir/$lab.tar.gz $HOME

# Khởi động container
USER root
CMD ["/bin/bash", "-c", "exec /sbin/init --log-target=journal 3>&1"]
